# Capture [/api/capture]

## Capture [POST]

+ Request request(application/json) 
  + Headers
      cnx-tenantid: 2ql3bti6juo (string,required)
      cnx-correlationid: 7e35a975-b76a-4a60-8e93-7aa329a56996 (string,optional)
      cnx-stackid: 7e35a975-b76a-4a60-8e93-7aa329a56996 (string,optional)
      cnx-environment-token: T1, T2, QA, SG (string,optional)
      cnx-userip: 127.0.0.1 (string,optional)
      cnx-unique-requestid: 7e35a975-b76a-4a60-8e93-7aa329a56996 (string,required)
      Content-Type: application/json (string,required)
      Accept-Language: en-US (string,optional)
      Accept-Encoding: Gzip, deflate (string,optional)
      Accept-Charset: UTF-8 (string,optional)
  + Attributes (request)

+ Response 200 (application/json)
  + Headers
      Content-Type: application/json (string,optional)
      cnx-correlationid: 0dc9e51a-fe55-4190-b2c5-8d2405539d47 (string,optional)
      cnx-transactionid: 6c4786ee-8afb-46f6-a0c6-89a3ca6b54c3 (string,optional)
      Accept-Encoding: gzip, deflate (string,optional)
