## formOfPayment
+ type: `Credit` (string) - sample description for type
+ source: `source sample value` (string) - sample description for source
+ currency: `USD` (string) - sample description for currency
