## request
+ orderId: `123456789` (string,required) - orderId description goes here
+ createdOn: `2020-01-01` (string,required) - orderId description goes here
+ info (bookingInfo,object) - description for booking info
+ paymentMethods (array[formOfPayment],fixed-type) - description for payment methods
+ type (occupantType,fixed-type) - description for occupant type
