## addressInfo

+ line1: `Address line 1` (string,optional)

+ line2: `Address line 2` (string,optional)

+ cityName: `Pune` (string,optional)

+ state (stateInfo,object)

+ countryCode": `IN` (string,optional)

+ postalCode: `411014` (string,optional)
