## captureResponse

+ transactionId:`1021XYZW` (string,required) - Payment Gateway Transaction Id to be used in subsequent transaction

+ statusCode: `Status Code` (string,required) - Response Status Code

+ statusMessage: `Status Message` (string,required) - Response Status Message
