## CaptureRequest

+ rootId:`` (string,required) - id returned by the first payment (authorization) operation

+ reconciliationId:`value1` (string,optional)  - Contains values like orderid, SPNR etc will be sent to Payment Gateway

+ merchantId:`` (string,required) - Merchant identitication

+ amount:`102.21` (number,required) - Transaction amount

+ currency:`INR` (string,optional) - Currency code

+ softDescriptor:`MERCHANT PRODUCT` (string,optional) - Descriptor code
