## cardInfo

+ token: `skfwefh$@fkew0fwy32ryr$#8ffjn3` (string,required) - Token Generated

+ number: `444433******1111` (string,required) - Card Number masked

+ issuedBy: `VI` (enum,optional) - Card Issued By
  + AX
  + BC
  + CA
  + DS
  + DC
  + E
  + JC
  + R
  + S
  + T
  + TO
  + VI

+ holderName: `John Doe` (string,optional) - Cardholder Name

+ cvv: `123` (number,required) - CVV
