## paymentMethodDetails

+ methodType: `Card` (enum,optional) - Payment method
  + ACH
  + ApplePay
  + Card
  + GooglePay
  + PayPal

+ card (cardInfo, object) - Different types of Payment methods for Card info
