## paymentRequest

+ amount: `102.21` (number,required) - Amount

+ currency: `USD` (string,required) - Currencies USD INR AUD BRL etc 15 more supported

+ merchantId (string,required) - Merchant Identification

+ reconciliationId: `value1` (string,optional) - like orderid, SPNR etc will be sent to Payment Gateway

+ paymentOperation: `Authorize` (enum, optional,fixed-type) - Used for all Authorize,Sale,Credit and  Default value is Authorize
	+ Authorize
	+ Credit
	+ Sale
  
+ softDescriptor: `MERCHANT PRODUCT`

+ dataExtensionFields (dataExtensionFieldsDetails,object)
